### ISSUE TITLE
not working in windows

### ISSUE THREAD

**Issue by punkmonday** [arquillian/arquillian-extension-liferay#45]
<details>
 <summary>not working in windows</summary>
 Maven home: C:\Program Files\apache-maven-3.3.3
 Java version: 1.8.0_101, vendor: Oracle Corporation
 Java home: C:\Program Files\Java\jdk1.8.0_101
 Default locale: en_US, platform encoding: UTF-8
 OS name: "windows", version: "7.x86_64", arch: "amd64", family: "windows"
</details>

**Comment by bartoszmajsak** [comment]
Thanks for reporting. Would you mind attaching a stacktrace too?

**Comment by csierra** [comment]
hey @punkmonday 

could you try with https://github.com/liferay-labs/arquillian-liferay

anyhow... as @bartoszmajsak suggest, could you provide us with more information about your issue?

Thx for reporting.

**Comment by bartoszmajsak** [comment]
@csierra shall we consider this repository obsolete?

**Comment by punkmonday** [comment]
org.jboss.arquillian.container.spi.client.container.LifecycleException:
Error connecting to Karaf MBeanServer:
at
org.jboss.arquillian.container.osgi.karaf.remote.KarafRemoteDeployableContainer.start(KarafRemoteDeployableContainer.java:77)
at
org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:199)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:163)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:157)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:255)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startContainer(ContainerLifecycleController.java:156)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
at
org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
at
org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
at
org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
at
org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:77)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:70)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forEachSuiteContainer(ContainerLifecycleController.java:221)
at
org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startSuiteContainers(ContainerLifecycleController.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
at
org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
at
org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
at
org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
at
org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
at
org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
at
org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
at
org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
at
org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
at
org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
at
org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
at
org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at
org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at
org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.get(FutureTask.java:205)
at
org.jboss.arquillian.container.osgi.jmx.JMXDeployableContainer.getMBeanServerConnection(JMXDeployableContainer.java:355)
at
org.jboss.arquillian.container.osgi.karaf.remote.KarafRemoteDeployableContainer.start(KarafRemoteDeployableContainer.java:74)
... 67 more

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  com.liferay.arquillian.sample.service.BasicPortletIntegrationTest: Error
connecting to Karaf MBeanServer:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 32.599 s
Finished at: 2016-11-30T17:19:00+08:00
Final Memory: 15M/430M
------------------------------------------------------------------------

2016-11-30 17:12 GMT+08:00 Bartosz Majsak <notifications@github.com>:

**Comment by csierra** [comment]
@punkmonday it looks like JMX can't be reached... make sure you configure JMX properly and that you have no other application listening on that port (Spotify usually uses the same port as JMX)

**Comment by punkmonday** [comment]
but i can use jconsole connect localhost:8099

2016-11-30 17:31 GMT+08:00 Carlos Sierra Andrés <notifications@github.com>:

**Comment by punkmonday** [comment]
and i closed  firewall already.

2016-11-30 18:15 GMT+08:00 Punk Flyer <punkflyer@gmail.com>:

**Comment by csierra** [comment]
have you tries with https://github.com/liferay-labs/arquillian-liferay?

**Comment by csierra** [comment]
hey @bartoszmajsak 

I have asked and yes... we can consider this repo obsolete in favor of the one I pasted above...

I guess I will update the README or do you plan to remove it?

**Comment by punkmonday** [comment]
@csierra  thank you , i tried https://github.com/liferay-labs/arquillian-liferay,i started my liferay7-ga3 server and jmx open(can open by jconsole),when i run test BasicPortletIntegrationTest,that's error:
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.liferay.arquillian.test.BasicPortletIntegrationTest
SLF4J: The requested version 1.5.11 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
十二月 01, 2016 4:06:03 下午 org.jboss.arquillian.drone.webdriver.factory.remote.reusable.ReusedSessionPermanentFileStorage readStore
信息: Reused session store is not available at C:\Users\w4u\.drone-webdriver-session-store, a new one will be created.
log4j:WARN No appenders could be found for logger (org.jboss.arquillian.container.test.spi.client.deployment.ApplicationArchiveProcessor).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.742 sec <<< FAILURE! - in com.liferay.arquillian.test.BasicPortletIntegrationTest
com.liferay.arquillian.test.BasicPortletIntegrationTest  Time elapsed: 4.742 sec  <<< ERROR!
java.lang.IllegalArgumentException: Not a valid OSGi bundle: 34f5aa1a-8874-49f5-9167-ff13d96b5717.jar: 40 assets
	at com.liferay.arquillian.container.osgi.remote.processor.OSGiAllInProcessor.process(OSGiAllInProcessor.java:114)
	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.applyApplicationProcessors(DeploymentGenerator.java:223)
	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.buildTestableDeployments(DeploymentGenerator.java:172)
	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.createTestableDeployments(DeploymentGenerator.java:148)
	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.generateDeployment(DeploymentGenerator.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:87)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:201)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:422)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:218)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:166)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.nio.file.FileSystemException: C:\Users\w4u\AppData\Local\Temp\34f5aa1a-8874-49f5-9167-ff13d96b5717.jar7f7e23fb-96b0-4a8d-8881-1e57d585908d793680586071878062.jar: 另一个程序正在使用此文件，进程无法访问。(  another program is using this file, and the process can not access it )

**Comment by csierra** [comment]
hey @punkmonday 

I am a bit confused because I see two different errors (and I am not sure if one of them is mistakenly attributed to the other). 

On one hand I see `Not a valid OSGi bundle: 34f5aa1a-8874-49f5-9167-ff13d96b5717.jar`. You can inspect the contents of the file that arquillian is trying to send using the `deploymentExportPath` option. 

On the other hand I see `another program is using this file, and the process can not access it` which I don't know why it might happen. Can you please figure out which processes are using the file? Maybe it is something we are provoking with the extension...

**Comment by punkmonday** [comment]
i found this line 100,when i comment out 100-102 ,it's ok,and it's java processes using this file
https://github.com/liferay-labs/arquillian-liferay/blob/master/arquillian-processor-osgi-allin/src/main/java/com/liferay/arquillian/container/osgi/remote/processor/service/ManifestManagerImpl.java

**Comment by csierra** [comment]
@punkmonday does it make any difference in your case changing it for File.delete()? I would have guessed this happens because the test infra spawns a new VM for the tests. Could you please test whether changing it with file.delete() makes any difference?

**Comment by punkmonday** [comment]
@csierra changging it with file.delete(),temporary files can not be deleted,file.delete() return false

**Comment by csierra** [comment]
oh... I see... 

then I guess the problem is the file is not closed. Could you `file.close()` before `file.delete()` and see if it works for you?

**Comment by punkmonday** [comment]
i change to file.deleteOnExit(); seems to be fine.

**Comment by csierra** [comment]
hey @punkmonday, 
would you like to send a pull request to https://github.com/liferay-labs/arquillian-liferay?

thx!

**Comment by bartoszmajsak** [comment]
Moved to https://github.com/liferay-labs/arquillian-liferay
